# Generated by Django 4.2.1 on 2023-05-14 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataTest', '0003_board_like_board_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataTest.customer'),
        ),
    ]
