# Generated by Django 4.2.1 on 2023-05-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataTest', '0006_alter_board_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='challenge',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('address', models.URLField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('rate', models.IntegerField()),
                ('Bigcategory', models.CharField(max_length=100)),
                ('smallcategory', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='comment',
            field=models.PositiveIntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='views',
            field=models.PositiveIntegerField(max_length=50, null=True),
        ),
    ]
