# Generated by Django 4.2.1 on 2023-05-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataTest', '0007_ch_like_alter_board_comment_alter_board_views_and_more'),
        ('dataTest', '0007_challenge_alter_board_comment_alter_board_views'),
    ]

    operations = [
    ]
