# Generated by Django 4.2 on 2023-05-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataTest', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ch_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataTest.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataTest.customer')),
            ],
        ),
    ]
