# Generated by Django 4.2.1 on 2023-05-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataTest', '0004_board_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user_id',
            new_name='userId',
        ),
    ]
