# Generated by Django 4.2.1 on 2023-05-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataTest', '0005_rename_user_id_board_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='userId',
            field=models.ForeignKey(db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataTest.customer'),
        ),
    ]
